Repository kuznia-rdzeni/transactron, pull requests merged in 2025-01, with the labels that each got.

#30 Transactron redesign: better proxying and cleaner implementation
  docs/transactions.md
  test/core/test_transactions.py
  test/lib/test_connectors.py
  test/lib/test_reqres.py
  test/lib/test_simultaneous.py
  test/lib/test_transformers.py
  test/test_methods.py
  test/test_simultaneous.py
  test/testing/test_validate_arguments.py
  transactron/core/__init__.py
  transactron/core/body.py
  transactron/core/manager.py
  transactron/core/method.py
  transactron/core/schedulers.py
  transactron/core/sugar.py
  transactron/core/transaction.py
  transactron/core/transaction_base.py
  transactron/graph.py
  transactron/lib/adapters.py
  transactron/lib/fifo.py
  transactron/lib/reqres.py
  transactron/lib/simultaneous.py
  transactron/lib/transformers.py
  transactron/testing/profiler.py
  transactron/utils/gen.py
  transactron/utils/transactron_helpers.py
Labels: refactor

#35 Fix testbench timeouts to stop simulation
  transactron/testing/infrastructure.py
Labels: bug

#33 Improved SimpleTestCircuit
  test/testing/test_method_mock.py
  transactron/core/method.py
  transactron/lib/adapters.py
  transactron/testing/infrastructure.py
  transactron/testing/method_mock.py
Labels: enhancement

#41 Fix memory banks for non-data shapes and test
  pyproject.toml
  test/lib/test_storage.py
  transactron/lib/storage.py
Labels: bug

#40 Move StableSelectingNetwork out of lib
  test/utils/amaranth_ext/test_elaboratables.py
  transactron/lib/connectors.py
  transactron/utils/amaranth_ext/elaboratables.py
Labels: refactor

#44 Look for Required/Provided annotations in base classes too
  pyproject.toml
  test/testing/test_method_mock.py
  transactron/testing/infrastructure.py
Labels: enhancement
