Repository kuznia-rdzeni/transactron, pull requests merged in 2025-02, with the labels that each got.

#39 Multi-ported memory
  test/lib/test_storage.py
  transactron/utils/amaranth_ext/memory.py
Labels: enhancement

#48 Tprof as script in pyproject.toml
  pyproject.toml
  transactron/cmd/__init__.py
  transactron/cmd/tprof.py
Labels: refactor

#50 Fix ManyToOneConnectTrans test
  test/lib/test_connectors.py
Labels: bug, tests

#51 Allow 0 Methods
  transactron/core/method.py
Labels: bug

#47 Orphaned simultaneous transactions fix
  test/lib/test_simultaneous.py
  transactron/core/manager.py
  transactron/core/transaction_base.py
Labels: bug

#53 One-hot mux circuit
  transactron/utils/amaranth_ext/elaboratables.py
  transactron/utils/amaranth_ext/memory.py
Labels: enhancement

#55 Fix combinational loop in multiport memory impls
  transactron/utils/amaranth_ext/memory.py
Labels: bug

#52 Nonexclusive wrapper
  test/lib/test_transformers.py
  transactron/lib/transformers.py
Labels: enhancement

#56 Conflict degree sort after priority topological sort
  pyproject.toml
  test/core/test_transactions.py
  transactron/core/manager.py
Labels: enhancement

#58 Fix make_hashable
  transactron/utils/data_repr.py
Labels: bug
